---
- hosts: all
  become: yes
  tasks:
    - name: Garantir que o SSH rejeite autenticacao por senha
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Reiniciar SSH

    - name: Bloquear login direto do root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Reiniciar SSH

  handlers:
    - name: Reiniciar SSH
      service:
        name: ssh
        state: restarted

- hosts: webservers
  become: yes
  tasks:
    - name: Instalar o Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Garantir que o Nginx esta ativo e habilitado no boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Criar pagina HTML personalizada identificando o no (para testes)
      copy:
        content: "<h1>Bem-vindo ao {{ inventory_hostname }} - LOWE</h1>"
        dest: /var/www/html/index.html        